pipeline {
    agent {
        docker {
            image 'node:8.12.0' 
            args '-p 3000:3000' 
        }
    }
	 environment {
        HOME = '.'
        CI = 'true'
    }
    stages {
         stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/ccastromar/real-world-nuxt.git'
            }
        }
        stage('Build') { 
            steps {
                
                sh 'npm install' 
            }
        }
        stage('Test') {
            steps {
                
                sh 'npm test'
               
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}